### ISSUE TITLE
 some questions about ‘env.spec.timestep_limit’ 

### ISSUE THREAD

**Issue by LiDuan1111** [daogiang993/InvertedPendulum-v1#1]
Is that the return of ‘env.spec.tomestep_limit’ for all gym environments  is 1000? What's the meaning of 'env.spec.timestep_limit'

**Comment by daogiang993** [comment]
timestep_limit is basically limiting the number of steps in an episode. For example, in this case the environment will perform maximum 1000 steps and set 'done' to True doesn't matter if it is really done.
It is not 1000 for all gym environments, but it is usually 1000 for MuJoCo environments.

**Comment by LiDuan1111** [comment]
OK,thank you very much!
But I still can not get that the number of steps in an episode is 1000,I mean,such as Humanoid,we hope that it's able to work as long as possible.
Or this limits means that I should try to train the neural networks until the humanoid can alaways get the reward at every step (total is 1000) of any  episode when testing?
I am sorry to disturb you~ Have a good day!

**Comment by daogiang993** [comment]
Basically, if an agent can perform 1000 steps in an episode, we assume it can keep it up forever to save simulation time.

**Comment by LiDuan1111** [comment]
Thank you~
